language: node_js
node_js:
  - "9"
  - "10"
  - "11"
  - "12"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - qtbase5-dev
      - build-essential
      - qt5-default
      - g++-5
      - x11-apps
      - imagemagick
before_install:
  - export CXX="g++-5"
install:
  - npm install
